kind: Template
apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
      name: ${NAME}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:latest'
      postCommit: {}
      resources: 
        requests:
          cpu: 500m
          memory: 1.5Gi
        limits:
          cpu: 1000m
          memory: 3Gi
      source:
        git:
          ref: ${SOURCE_REPOSITORY_REF}
          uri: ${SOURCE_REPOSITORY_URL}
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'caddy-s2i-builder:latest'
            namespace: ${NAMESPACE}
        type: Source
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
      name: ${NAME}
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: mautic-subscription-app
- description: Github repository URL
  displayName: SOURCE_REPOSITORY_URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/bcgov/Mautic-Subscription-App
- description: Github repository branch
  displayName: SOURCE_REPOSITORY_REF
  name: SOURCE_REPOSITORY_REF
  required: true
  value: ''
- description: Namespace name
  displayName: NAMESPACE
  name: NAMESPACE
  required: true
  value: ''
  oc4 delete bc,dc mautic-subscription-app
  oc4 process -f mautic.bc.yaml -p SOURCE_REPOSITORY_REF=initial-setup -p NAMESPACE=de0974-tools | oc4 apply -f -
  oc4 process -f mautic.dc.yaml | oc4 apply -f -