metadata:
  name: mautic-subscribe-workflow
  namespace: de0974-tools
spec:
  templates:
    - name: main
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: clone
            template: clone
            arguments: {}
        - - name: build-deploy-mautic-tools
            template: build-deploy-mautic-tools
            arguments: {}
        - - name: deploy-mautic-dev
            template: deploy-mautic-dev
            arguments: {}    
        # - - name: deploy-mautic-test
        #     template: deploy-mautic-test
        #     arguments: {}  

    - name: clone
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/alpine/git:v2.26.2'
        args:
          - clone
          - '--depth'
          - '1'
          - '--branch'
          - '{{workflow.parameters.BRANCH}}'
          - '--single-branch'
          - '{{workflow.parameters.REPO}}'
        workingDir: /mnt/vol
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    - name: build-deploy-mautic-tools
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/openshift/origin-cli:latest'
        command:
          - sh
          - '-c'
        args:
          - >-
            oc process -f openshift/mautic.bc.yaml 
            -p SOURCE_REPOSITORY_REF={{workflow.parameters.BRANCH}}
            -p NAMESPACE={{workflow.parameters.TOOLS_NAMESPACE}}
            -p IMAGE_NAME={{workflow.parameters.NAME}} 
            -p IMAGE_TAG={{workflow.parameters.IMAGE_TAG}} 
            -p REACT_APP_SSO_BASE_URL={{workflow.parameters.SSO_BASE_URL}}
            -p REACT_APP_SSO_CLIENT_ID={{workflow.parameters.SSO_CLIENT_ID}}
            -p REACT_APP_SSO_REALM_NAME={{SSO_REALM_NAME}}
            -p SUFFIX={{workflow.parameters.SUFFIX}}
            | oc apply -f - ; 
            oc start-build -w mautic-subscription-app{{workflow.parameters.SUFFIX}}
        workingDir: /mnt/vol/Mautic-Subscription-App
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    - name: deploy-mautic-dev
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/openshift/origin-cli:latest'
        command:
          - sh
          - '-c'
        args: 
          - >-
            oc create configmap test-config --from-file=public/config/form.json;
            oc process -f openshift/mautic.dc.yaml 
            -p SUFFIX={{workflow.parameters.SUFFIX}}
            -p IMAGE_NAME={{workflow.parameters.NAME}} 
            -p IMAGE_NAMESPACE={{workflow.parameters.TOOLS_NAMESPACE}} 
            -p IMAGE_TAG={{workflow.parameters.IMAGE_TAG}} 
            -n {{workflow.parameters.DEV_NAMESPACE}}
            | oc apply -f - -n {{workflow.parameters.DEV_NAMESPACE}}
        workingDir: /mnt/vol/Mautic-Subscription-App
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    # - name: deploy-mautic-test
    #   arguments: {}
    #   inputs: {}
    #   outputs: {}
    #   metadata: {}
    #   container:
    #     name: ''
    #     image: 'docker.io/openshift/origin-cli:latest'
    #     command:
    #       - sh
    #       - '-c'
    #     args: 
    #       - >-
    #         oc process -f mautic.dc.yaml 
    #         -p SUFFIX={{workflow.parameters.SUFFIX}} 
    #         -n {{workflow.parameters.TEST_NAMESPACE}}
    #         | oc apply -f - -n {{workflow.parameters.TEST_NAMESPACE}}
    #     workingDir: /mnt/vol/Mautic-Subscription-App
    #     resources:
    #       limits:
    #         cpu: 100m
    #         memory: 512Mi
    #       requests:
    #         cpu: 50m
    #         memory: 256Mi
    #     volumeMounts:
    #       - name: work
    #         mountPath: /mnt/vol

  entrypoint: main
  arguments: {}
  serviceAccountName: workflow-creator
  volumeClaimTemplates:
    - metadata:
        name: work
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
        storageClassName: netapp-file-standard
      status: {}
  imagePullSecrets:
    - name: dockerhub-secret-mautic

