kind: Template
apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      name: ${NAME}
      labels:
        app: ${NAME}${SUFFIX}
        group: ${NAME}
        deploymentconfig: ${NAME}${SUFFIX}
        app-name: ${NAME}${SUFFIX}
    spec:
      lookupPolicy:
        local: false
    status: {}
  - apiVersion: v1
    data:
      Caddyfile: |
          # Where caddy should listen
          :2015

          # Turn on the Web/file server
          file_server

          # The site root
          root * /opt/app-root/src

          # Because we should
          encode zstd gzip

          # This rewrite rule may be required to get React apps
          # to deal with trailing slashes properly.
          @filter {
          	not path_regexp ^\/0.0.0.0
          	file {
          		try_files {path} {path}/ /?url={uri}
          	}
          }
          # rewrite @try_files {http.matchers.file.relative}
          try_files {path} {path}/ index.html

          # On OCP we should log to stdout so Prometheus can
          # slurp up the logs for human consumption.
          log {
            #errors stdout
            output stdout 
            format single_field common_log
            level info
          }
        

    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: caddy-${NAME}${SUFFIX}
      labels:
        app: ${NAME}${SUFFIX}
        group: ${NAME}
        deploymentconfig: ${NAME}${SUFFIX}
        app-name: ${NAME}${SUFFIX}
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
      strategy:
        resources: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            deploymentconfig: ${NAME}${SUFFIX}
        spec:
          containers:
            - image: '${IMAGE_REGISTRY}/${TARGET_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}'
              name: ${NAME}${SUFFIX}
              ports:
                - containerPort: 2015
                  protocol: TCP
              resources: {}
              volumeMounts:
              - name: caddy-${NAME}${SUFFIX}
                mountPath: /opt/app-root/etc/Caddyfile
                readOnly: true
                subPath: Caddyfile
              - name: form-config-volume
                mountPath: /src/form-config
              - name: sso-config-volume
                mountPath: /src/sso-config
          volumes:
          - name: caddy-${NAME}${SUFFIX}
            configMap:
              defaultMode: 420
              name: caddy-${NAME}${SUFFIX}
          - name: form-config-volume
            configMap:
              name: mautic-form-config
          - name: sso-config-volume
            configMap:
              name: mautic-sso-config
      test: false
      triggers: 
        - type: ConfigChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: ${NAME}${SUFFIX}
        app.kubernetes.io/component: ${NAME}${SUFFIX}
        app.kubernetes.io/instance: ${NAME}${SUFFIX}
        group: ${NAME}
      name: ${NAME}${SUFFIX}
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: ${NAME}${SUFFIX}
        app.kubernetes.io/component: ${NAME}${SUFFIX}
        app.kubernetes.io/instance: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        app: ${NAME}${SUFFIX}
        app.kubernetes.io/component: ${NAME}${SUFFIX}
        app.kubernetes.io/instance: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
    spec:
      host: ""
      port:
        targetPort: 2015-tcp
      to:
        kind: ""
        name: ${NAME}${SUFFIX}
        weight: null
      tls:
        termination: Edge
    status:
      ingress: null
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: mautic-subscription-app
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: true
  value: -dev
- description: A name used for all objects
  displayName: IMAGE_NAME
  name: IMAGE_NAME
  required: true
  value: mautic-subscription-app
- description: A name used for all objects
  displayName: IMAGE_REGISTRY
  name: IMAGE_REGISTRY
  required: true
  value: image-registry.openshift-image-registry.svc:5000
- description: A name used for all objects
  displayName: IMAGE_TAG
  name: IMAGE_TAG
  required: true
  value: dev
- description: A name used for all objects
  displayName: TARGET_NAMESPACE
  name: TARGET_NAMESPACE
  required: true
  value: de0974-dev

