kind: Template
apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      name: ${APP_NAME}-api
      labels:
        app: ${APP_NAME}-api
        name: ${APP_NAME}-api-${IMAGE_TAG}
    spec:
      lookupPolicy:
        local: false
    status: {}

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${APP_NAME}-api-${IMAGE_TAG}
      strategy:
        resources: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            deploymentconfig: ${APP_NAME}-api-${IMAGE_TAG}
        spec:
          containers:
            - image: '${IMAGE_REGISTRY}/${TARGET_NAMESPACE}/${APP_NAME}-api:${IMAGE_TAG}'
              imagePullPolicy: Always
              name: ${APP_NAME}-api-${IMAGE_TAG}
              ports:
                - containerPort: 2015
                  protocol: TCP
              resources: {}
      test: false
      triggers: 
        - type: ImageChange
          imageChangeParams:
            automatic: true 
            from:
              kind: "ImageStreamTag"
              name: "${APP_NAME}-api:${IMAGE_TAG}"
              namespace: "${TARGET_NAMESPACE}"
            containerNames:
              - ${APP_NAME}-api-${IMAGE_TAG}
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: ${APP_NAME}-api
        name: ${APP_NAME}-api-${IMAGE_TAG}
      name: ${APP_NAME}-api-${IMAGE_TAG}
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        deploymentconfig: ${APP_NAME}-api-${IMAGE_TAG}
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: ${APP_NAME}-api
        name: ${APP_NAME}-api-${IMAGE_TAG}
      name: ${APP_NAME}-api-${IMAGE_TAG}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        app: ${APP_NAME}-api
        name: ${APP_NAME}-api-${IMAGE_TAG}
      name: ${APP_NAME}-api-${IMAGE_TAG}
    spec:
      host: ""
      port:
        targetPort: 2015-tcp
      to:
        kind: ""
        name: ${APP_NAME}-api-${IMAGE_TAG}
        weight: null
      tls:
        termination: Edge
        insecureEdgeTerminationPolicy: Redirect
    status:
      ingress: null  
parameters:
- description: A name used for all objects
  displayName: App Name
  name: APP_NAME
  required: true
- description: A name used for all objects
  displayName: IMAGE_REGISTRY
  name: IMAGE_REGISTRY
  required: true
- description: A name used for all objects
  displayName: IMAGE_TAG
  name: IMAGE_TAG
  required: true
- description: A name used for all objects
  displayName: TARGET_NAMESPACE
  name: TARGET_NAMESPACE
  required: true

