kind: Template
apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        name: ${NAME}-${IMAGE_TAG}
        app: ${NAME}
      name: ${NAME}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:${IMAGE_TAG}'
      postCommit: {}
      resources: 
        requests:
          cpu: 500m
          memory: 1.5Gi
        limits:
          cpu: 1000m
          memory: 3Gi
      source:
        git:
          ref: ${SOURCE_REPOSITORY_REF}
          uri: ${SOURCE_REPOSITORY_URL}
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'caddy-s2i-builder:latest'
            namespace: ${TOOLS_NAMESPACE}
        type: Source
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ${NAME}
        name: ${NAME}-${IMAGE_TAG}
      name: ${NAME}-${IMAGE_TAG}
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
- description: Github repository URL
  displayName: SOURCE_REPOSITORY_URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/bcgov/Mautic-Subscription-App
- description: Github repository branch
  displayName: SOURCE_REPOSITORY_REF
  name: SOURCE_REPOSITORY_REF
  required: true
  value: ''
- description: Tools namespace name
  displayName: TOOLS_NAMESPACE
  name: TOOLS_NAMESPACE
  required: true
  value: ''
- description: A name used for all objects
  displayName: IMAGE_TAG
  name: IMAGE_TAG
  required: true